### ISSUE TITLE
symfony 5

### ISSUE THREAD

**Issue by psohm** [Alsatian67/FormBundle#10]
can you upgrade the package to symfony 5.0 ?

alsatian/form-bundle dev-master requires symfony/framework-bundle ~2.8|~3.0|~4.0 -> satisfiable by symfony/framework-bundle[v4.4.3] but these conflict with your requirements or minimum-stability.
    - alsatian/form-bundle dev-master requires symfony/framework-bundle ~2.8|~3.0|~4.0 -> satisfiable by symfony/framework-bundle[v4.4.3] but these conflict with your requirements or minimum-stability.
    - Installation request for alsatian/form-bundle dev-master -> satisfiable by alsatian/form-bundle[dev-master].

Hopla merci ! :)

**Comment by psohm** [comment]
I'm thinking about the package for composer
it has a requirement on sf 4

**Comment by Alsatian67** [comment]
Requirement updated.
Let me know if problems occured with Symfony 5.0
This repository has no tests.

**Comment by psohm** [comment]
hello
it doesn't work

I think you should autowire the parameters in that file
$router => RouterInterface $router
but the other one I don't know how to replace it

ArgumentCountError:
Too few arguments to function Alsatian\FormBundle\Form\AbstractRoutableType::__construct(), 0 passed in C:\Travail\Emporium\EmporiumWeb\vendor\symfony\form\FormRegistry.php on line 91 and exactly 2 expected

**Comment by Alsatian67** [comment]
Did you enable the bundle in the AppKernel.php file ? (See readme/installation)

This is not automated in this bundle. I have to add Flex recipes to do it.

**Comment by Alsatian67** [comment]
Then you have to enable the ExtensibleEntityType in config/

**Comment by psohm** [comment]
I think you're right. I forgot the extension in twig.
ready to be released I think 👍

**Comment by Alsatian67** [comment]
The package has been updated.
