### ISSUE TITLE
add some more info on how to implement

### ISSUE THREAD

**Issue by bluppfisk** [Alsatian67/FormBundle#2]
It's not entirely clear to me whether it will load the Select2 hook automatically and how it sets the parameters of Select2. Perhaps you could some info on that in the docs?

**Comment by Alsatian67** [comment]
The aim of this bundle is only to do the server side work (allow new choices to be submitted).
You have to integrate Select2 yourself.

As example I wrote a JQuery implmentation at the end of the documentation.
