### ISSUE TITLE
Problem with the ExtensibleChoiceType

### ISSUE THREAD

**Issue by Namalee** [Alsatian67/FormBundle#20]
In your ExtensibleSubscriber, you should add line 64 to 69 (in the ExtensibleChoiceType case) a case like that : 

```
elseif (is_object($data)){
    $choices = [$this->getValue($data,$options['choice_label']) => $data->getId()];
}
```

**Comment by Namalee** [comment]
note : this in the case when the field work with entities but the EntityType is not possible to use. Exemple, when we use the search or create new entry feature of the select2 library. Because of the "create new entry", the EntyType can't work so we have to fall back to the ChoiceType but that one, in your actual code can't handle objects. With the proposed fix, it will.

**Comment by Alsatian67** [comment]
Something like that will be specific to your usage, and I don't want to add this kind of extra features.

You could do it in your own subscriber, fork this repo or download it and put it in your src direvmctry.

**Comment by Namalee** [comment]
well it was not only for my use but to make the "Dynamic option creation" feature of select2 [(https://select2.org/tagging)](https://select2.org/tagging) work with your bundle beacause, currently there is no way to use it with your bundle.

**Comment by Alsatian67** [comment]
ExtensibleChoiceType aims to extend ChoiceType.
ChoiceType should not implement Entity logic.

The ExtensibleEntityType could implement a new feature "Create entity if not exist" but the way it is created is app specific ...
So, I don't want to implement something like that.

You should be able to implement your own logic on top of the ExtensibleChoiceType.
