### ISSUE TITLE
Clarify something in the documentation, please

### ISSUE THREAD

**Issue by danbettles** [Alsatian67/FormBundle#25]
Hello

Thanks very much for the bundle: it's spot on.

Please could you help me with something in the documentation?  What does the following mean?

> Configuration : Insert %alsatian_form.parameters.extensible_entity.attr_class% as class for the HTML select.

I thought it meant I could do the following.

```php
//...
->add('something', ExtensibleEntityType::class, [
    //...
    'attr' => [
        'class' => 'something %alsatian_form.parameters.extensible_entity.attr_class%',
    ],
])
//...
```

But that doesn't work.

Could you clarify, please?

Many thanks,
Dan

**Comment by Alsatian67** [comment]
If you define the parameter %alsatian_form.parameters.extensible_entity.attr_class% "globaly" in the config/ dir, the value of this parameter will be used by each ExtensibleEntity type without other configuration.

If you want to set the class only on thus form, forget this feature and write your desired class directly in 'attr'.
