### ISSUE TITLE
Symfony 6 warnings

### ISSUE THREAD

**Issue by FluffyDiscord** [Alsatian67/FormBundle#26]
Please accept these pull requests as they fix symfony 6+ warnings

Fix Symfony 6 Warning - ExtensibleSubscriber https://github.com/Alsatian67/FormBundle/pull/22
Fix Symfony 6 Warning - Configuration https://github.com/Alsatian67/FormBundle/pull/23
Fix Symfony 6 Warning - Form Types https://github.com/Alsatian67/FormBundle/pull/24

Reasons to move on:
- PHP 5.6 is no longer being supported (even hosting services are no longer offering this option, basically dead) https://github.com/Alsatian67/FormBundle/pull/22#issuecomment-1121634366
- you can keep old php support by releasing new major version, eg. v2.0.0 with strict php 7.3+ (or better - 8.1+) version requirement
- lower number of warnings in symfony profiler ;)

**Comment by Alsatian67** [comment]
Thank you for the method. I think it's time to merge the changes.

I wanted to restrict the new major version on Symfony >= 4.4 (to remove [1 old method](https://github.com/Alsatian67/FormBundle/commit/508bbfae325c7befdafcfe687c47253851156144)), => Then Php 7.1.3 as sf 4.4 requires it.

Is there any reason to chose php 7.3 or 8.1 ?

**Comment by FluffyDiscord** [comment]
> Is there any reason to chose php 7.3 or 8.1 ?

 There is *no real need* to restrict it to 7.3 or 8.1. I would suggest tho following at least the symfony LTS release requirements, which is no longer symfony 4.4 (its in "bug fixes stage" only), but 5.4 and making this new bundle version to require php 7.2 https://symfony.com/releases/5.4. This package is stable and nothing is missing on symfony 4.4, so theres no real reason to restrict it

This decision is purely on you though. As long as my warnings go away, I am happy 😊

**Comment by Alsatian67** [comment]
Done in minor version 1.1.0
Requirements are set on Symfony >= 4.4
