### ISSUE TITLE
Compile Error: Declaration of Alsatian\FormBundle\Form\Extensions\ExtensibleExtension::getExtendedTypes() must be compatible with Symfony\Component\Form\FormTypeExtensionInterface::getExtendedTypes(): Traversable|array

### ISSUE THREAD

**Issue by wucherpfennig** [Alsatian67/FormBundle#28]
https://github.com/Alsatian67/FormBundle/releases/tag/1.0.2

```
Compile Error: Declaration of Alsatian\FormBundle\Form\Extensions\ExtensibleExtension::getExtendedTypes() must be compatible with Symfony\Component\Form\FormTypeExtensionInterface::getExtendedTypes(): Traversable|array
```

I will submit a PR quickly

**Comment by wucherpfennig** [comment]
Hmm I see on `master` you already have added the `iterable` as return type...

**Comment by Alsatian67** [comment]
I'm just working on the integration of your mai 2022 suggestions ...
Then you could update it to 1.1.0 (Sf >= 4.4)

**Comment by Alsatian67** [comment]
As I wanted to keep the 1.0.x tags for Sf < 4.4, I though this old branch should stay compatible with php < 7.1 (interable return type introduction) and removed that return type to retablish this compatibility.

**Comment by wucherpfennig** [comment]
I saw sorry. I just ran into this "issue" while updating ;-) appreciate your work 💪🏻

**Comment by Alsatian67** [comment]
But I don't understand why it does a compile error ? Are you running a symfony version which make this requirement strict ?

Shouldn't it be a deprecation message like all return types you proposed ?

**Comment by wucherpfennig** [comment]
I do not know ^^ It should yeas. I am currently running on 6.2.4.

Checking the file https://github.com/Alsatian67/FormBundle/blob/1.0.2/Form/Extensions/ExtensibleExtension.php on the v1.0.2 tag there is no return type defined.

Checking the file https://github.com/Alsatian67/FormBundle/blob/1.0.1/Form/Extensions/ExtensibleExtension.php on the v1.0.1 there is and works fine

**Comment by Alsatian67** [comment]
OK, I will create a v1.0.3 restricted on Sf < 4.4, then you would have to update to the upcomming v1.1.0

**Comment by Alsatian67** [comment]
Please let me know if the 1.1.0 works (and without deprecation warnings).

**Comment by wucherpfennig** [comment]
Thank you for your efforts! works flawlessly (v1.1.0)
